name: Daily Kaggle Dataset Fetch

on:
    schedule:
        - cron: '0 0 * * *'  # Runs every day at midnight UTC
    workflow_dispatch:

jobs:
    fetch_datasets:
        runs-on: ubuntu-latest
        env:
            GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Set up Kaggle API credentials
              run: |
                mkdir -p ~/.kaggle
                echo '${{ secrets.KAGGLE_JSON }}' > ~/.kaggle/kaggle.json
                chmod 600 ~/.kaggle/kaggle.json
              
            - name: Debug - Confirm kaggle.json structure (TEMP)
              run: cat ~/.kaggle/kaggle.json
            
            - name: Fetch datasets
              run: |
                python fetch_kaggle.py

            - name: Commit and push changes
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --local user.name "github-actions[bot]"
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "🔄 Daily update: trending datasets" || echo "No changes to commit"
                git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}